/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libglug_timer_ContinuousTimer */

#ifndef _Included_org_libglug_timer_ContinuousTimer
#define _Included_org_libglug_timer_ContinuousTimer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libglug_timer_ContinuousTimer
 * Method:    alloc
 * Signature: (Lorg/libglug/Allocator;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_libglug_timer_ContinuousTimer_alloc
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_libglug_timer_ContinuousTimer
 * Method:    free
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_libglug_timer_ContinuousTimer_free
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_libglug_timer_ContinuousTimer
 * Method:    start
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_libglug_timer_ContinuousTimer_start
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_libglug_timer_ContinuousTimer
 * Method:    pause
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_libglug_timer_ContinuousTimer_pause
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_libglug_timer_ContinuousTimer
 * Method:    reset
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_libglug_timer_ContinuousTimer_reset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_libglug_timer_ContinuousTimer
 * Method:    delta
 * Signature: (Ljava/nio/ByteBuffer;Lorg/libglug/timer/Time;)V
 */
JNIEXPORT void JNICALL Java_org_libglug_timer_ContinuousTimer_delta
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_libglug_timer_ContinuousTimer
 * Method:    runTime
 * Signature: (Ljava/nio/ByteBuffer;Lorg/libglug/timer/Time;)V
 */
JNIEXPORT void JNICALL Java_org_libglug_timer_ContinuousTimer_runTime
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_libglug_timer_ContinuousTimer
 * Method:    state
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_libglug_timer_ContinuousTimer_state
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_libglug_timer_ContinuousTimer
 * Method:    timerRes
 * Signature: (Lorg/libglug/timer/Time;)V
 */
JNIEXPORT void JNICALL Java_org_libglug_timer_ContinuousTimer_timerRes
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
