/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libglug_timer_UptimeTimer */

#ifndef _Included_org_libglug_timer_UptimeTimer
#define _Included_org_libglug_timer_UptimeTimer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libglug_timer_UptimeTimer
 * Method:    alloc
 * Signature: (Lorg/libglug/Allocator;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_libglug_timer_UptimeTimer_alloc
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_libglug_timer_UptimeTimer
 * Method:    free
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_libglug_timer_UptimeTimer_free
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_libglug_timer_UptimeTimer
 * Method:    start
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_libglug_timer_UptimeTimer_start
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_libglug_timer_UptimeTimer
 * Method:    pause
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_libglug_timer_UptimeTimer_pause
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_libglug_timer_UptimeTimer
 * Method:    reset
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_libglug_timer_UptimeTimer_reset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_libglug_timer_UptimeTimer
 * Method:    delta
 * Signature: (Ljava/nio/ByteBuffer;Lorg/libglug/timer/Time;)V
 */
JNIEXPORT void JNICALL Java_org_libglug_timer_UptimeTimer_delta
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_libglug_timer_UptimeTimer
 * Method:    runTime
 * Signature: (Ljava/nio/ByteBuffer;Lorg/libglug/timer/Time;)V
 */
JNIEXPORT void JNICALL Java_org_libglug_timer_UptimeTimer_runTime
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_libglug_timer_UptimeTimer
 * Method:    state
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_libglug_timer_UptimeTimer_state
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_libglug_timer_UptimeTimer
 * Method:    timerRes
 * Signature: (Lorg/libglug/timer/Time;)V
 */
JNIEXPORT void JNICALL Java_org_libglug_timer_UptimeTimer_timerRes
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
